# Generated by Django 3.2.3 on 2021-11-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, verbose_name='科目名')),
                ('subject_code', models.CharField(max_length=10, verbose_name='授業コード')),
                ('pass_or_fail', models.CharField(blank=True, max_length=3, verbose_name='合否')),
            ],
        ),
    ]
