# Generated by Django 3.2.3 on 2021-11-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100, verbose_name='科目名')),
                ('subject_code', models.CharField(max_length=10, verbose_name='授業コード')),
                ('credit', models.FloatField(default=0, verbose_name='単位数')),
                ('compulsory_or_elective', models.CharField(blank=True, max_length=100, verbose_name='必修・選択')),
            ],
        ),
        migrations.CreateModel(
            name='General_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100, verbose_name='科目名')),
                ('subject_code', models.CharField(max_length=10, verbose_name='授業コード')),
                ('credit', models.FloatField(default=0, verbose_name='単位数')),
                ('compulsory_or_elective', models.CharField(blank=True, max_length=100, verbose_name='必修・選択')),
            ],
        ),
        migrations.CreateModel(
            name='My_Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, verbose_name='科目名')),
                ('subject_code', models.CharField(max_length=10, verbose_name='授業コード')),
                ('pass_or_fail', models.IntegerField(blank=True, default=0, verbose_name='合否')),
            ],
        ),
        migrations.CreateModel(
            name='System_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100, verbose_name='科目名')),
                ('subject_code', models.CharField(max_length=10, verbose_name='授業コード')),
                ('credit', models.FloatField(default=0, verbose_name='単位数')),
                ('compulsory_or_elective', models.CharField(blank=True, max_length=100, verbose_name='必修・選択')),
            ],
        ),
    ]
