# Generated by Django 3.2.3 on 2021-11-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proffesional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100, verbose_name='科目名')),
                ('subject_code', models.CharField(max_length=10, verbose_name='授業コード')),
                ('credit', models.IntegerField(verbose_name='単位数')),
                ('compulsory_or_elective', models.CharField(blank=True, max_length=100, verbose_name='必修・選択')),
            ],
        ),
    ]
