# Generated by Django 3.2.3 on 2021-11-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proffesional', '0002_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_subject',
            name='credit',
            field=models.FloatField(default=0, verbose_name='単位数'),
        ),
        migrations.AlterField(
            model_name='my_grades',
            name='pass_or_fail',
            field=models.IntegerField(blank=True, default=0, verbose_name='合否'),
        ),
    ]
