# Generated by Django 4.0 on 2022-01-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proffesional', '0002_auto_20211204_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_foreignlang_subject_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100, verbose_name='科目名')),
                ('subject_code', models.CharField(max_length=10, verbose_name='授業コード')),
                ('credit', models.FloatField(default=0, verbose_name='単位数')),
                ('compulsory_or_elective', models.CharField(blank=True, max_length=100, verbose_name='必修・選択')),
            ],
        ),
        migrations.CreateModel(
            name='General_human_subject_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100, verbose_name='科目名')),
                ('subject_code', models.CharField(max_length=10, verbose_name='授業コード')),
                ('credit', models.FloatField(default=0, verbose_name='単位数')),
                ('compulsory_or_elective', models.CharField(blank=True, max_length=100, verbose_name='必修・選択')),
            ],
        ),
        migrations.CreateModel(
            name='General_local_subject_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100, verbose_name='科目名')),
                ('subject_code', models.CharField(max_length=10, verbose_name='授業コード')),
                ('credit', models.FloatField(default=0, verbose_name='単位数')),
                ('compulsory_or_elective', models.CharField(blank=True, max_length=100, verbose_name='必修・選択')),
            ],
        ),
        migrations.CreateModel(
            name='System_common_subject_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100, verbose_name='科目名')),
                ('subject_code', models.CharField(max_length=10, verbose_name='授業コード')),
                ('credit', models.FloatField(default=0, verbose_name='単位数')),
                ('compulsory_or_elective', models.CharField(blank=True, max_length=100, verbose_name='必修・選択')),
            ],
        ),
        migrations.CreateModel(
            name='System_subject_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100, verbose_name='科目名')),
                ('subject_code', models.CharField(max_length=10, verbose_name='授業コード')),
                ('credit', models.FloatField(default=0, verbose_name='単位数')),
                ('compulsory_or_elective', models.CharField(blank=True, max_length=100, verbose_name='必修・選択')),
            ],
        ),
    ]
